version: '3.9'

services:

  db:
    image: postgres:latest
    ports:
      - '5431:5432'
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_BASE}"
