"""Initial migration

Revision ID: b790b83a218b
Revises:
Create Date: 2025-02-04 14:10:57.466685

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b790b83a218b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "elements",
        sa.Column("en_name", sa.String(length=30), nullable=False),
        sa.Column("ru_name", sa.String(length=30), nullable=False),
        sa.Column("ru_text", sa.Text(), nullable=True),
        sa.Column("en_text", sa.Text(), nullable=True),
        sa.Column("is_positive", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("en_name"),
        sa.UniqueConstraint("ru_name"),
    )
    op.create_index(op.f("ix_elements_id"), "elements", ["id"], unique=True)
    op.create_table(
        "haircutting_days",
        sa.Column("moon_day", sa.Integer(), nullable=False),
        sa.Column("en_name", sa.String(length=100), nullable=False),
        sa.Column("ru_name", sa.String(length=100), nullable=False),
        sa.Column("is_inauspicious", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("moon_day"),
    )
    op.create_index(
        op.f("ix_haircutting_days_id"), "haircutting_days", ["id"], unique=True
    )
    op.create_table(
        "la_positions",
        sa.Column("moon_day", sa.Integer(), nullable=False),
        sa.Column("en_name", sa.String(length=100), nullable=False),
        sa.Column("ru_name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("moon_day"),
    )
    op.create_index(
        op.f("ix_la_positions_id"), "la_positions", ["id"], unique=True
    )
    op.create_table(
        "skylight_arches",
        sa.Column("moon_day", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=10), nullable=False),
        sa.Column("en_desc", sa.String(length=100), nullable=False),
        sa.Column("ru_desc", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("moon_day"),
    )
    op.create_index(
        op.f("ix_skylight_arches_id"), "skylight_arches", ["id"], unique=True
    )
    op.create_table(
        "users",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=True)
    op.create_table(
        "yelam",
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("en_name", sa.String(length=30), nullable=False),
        sa.Column("ru_name", sa.String(length=30), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("month"),
    )
    op.create_index(op.f("ix_yelam_id"), "yelam", ["id"], unique=True)
    op.create_table(
        "day_info",
        sa.Column("date", sa.String(length=10), nullable=False),
        sa.Column("moon_day", sa.String(length=15), nullable=False),
        sa.Column("elements_id", sa.Integer(), nullable=False),
        sa.Column("arch_id", sa.Integer(), nullable=False),
        sa.Column("la_id", sa.Integer(), nullable=False),
        sa.Column("yelam_id", sa.Integer(), nullable=False),
        sa.Column("haircutting_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["arch_id"],
            ["skylight_arches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["elements_id"],
            ["elements.id"],
        ),
        sa.ForeignKeyConstraint(
            ["haircutting_id"],
            ["haircutting_days.id"],
        ),
        sa.ForeignKeyConstraint(
            ["la_id"],
            ["la_positions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["yelam_id"],
            ["yelam.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("date"),
    )
    op.create_index(op.f("ix_day_info_id"), "day_info", ["id"], unique=True)
    op.create_table(
        "descriptions",
        sa.Column("en_name", sa.String(), nullable=False),
        sa.Column("ru_name", sa.String(), nullable=True),
        sa.Column("ru_text", sa.Text(), nullable=True),
        sa.Column("en_text", sa.Text(), nullable=True),
        sa.Column("link", sa.String(), nullable=True),
        sa.Column("day_info_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["day_info_id"], ["day_info.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_descriptions_id"), "descriptions", ["id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_descriptions_id"), table_name="descriptions")
    op.drop_table("descriptions")
    op.drop_index(op.f("ix_day_info_id"), table_name="day_info")
    op.drop_table("day_info")
    op.drop_index(op.f("ix_yelam_id"), table_name="yelam")
    op.drop_table("yelam")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_skylight_arches_id"), table_name="skylight_arches")
    op.drop_table("skylight_arches")
    op.drop_index(op.f("ix_la_positions_id"), table_name="la_positions")
    op.drop_table("la_positions")
    op.drop_index(
        op.f("ix_haircutting_days_id"), table_name="haircutting_days"
    )
    op.drop_table("haircutting_days")
    op.drop_index(op.f("ix_elements_id"), table_name="elements")
    op.drop_table("elements")
    # ### end Alembic commands ###
