"""Изменил колонки элементов в таблици DayInfo

Revision ID: 8a5fe215cd3d
Revises: 80a68c104c53
Create Date: 2025-02-04 11:46:46.261028

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8a5fe215cd3d"
down_revision: Union[str, None] = "80a68c104c53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("day_info", sa.Column("elements_id", sa.Integer(), nullable=False))
    op.drop_constraint("day_info_second_element_id_fkey", "day_info", type_="foreignkey")
    op.drop_constraint("day_info_first_element_id_fkey", "day_info", type_="foreignkey")
    op.create_foreign_key(None, "day_info", "elements", ["elements_id"], ["id"])
    op.drop_column("day_info", "first_element_id")
    op.drop_column("day_info", "second_element_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "day_info",
        sa.Column("second_element_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "day_info",
        sa.Column("first_element_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "day_info", type_="foreignkey")
    op.create_foreign_key(
        "day_info_first_element_id_fkey", "day_info", "elements", ["first_element_id"], ["id"]
    )
    op.create_foreign_key(
        "day_info_second_element_id_fkey", "day_info", "elements", ["second_element_id"], ["id"]
    )
    op.drop_column("day_info", "elements_id")
    # ### end Alembic commands ###
