"""в таблицу Events добавлен столбец is_mutable

Revision ID: 194abfa3945f
Revises: 72b5baca7b9d
Create Date: 2025-02-08 12:15:34.330747

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "194abfa3945f"
down_revision: Union[str, None] = "72b5baca7b9d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events", sa.Column("is_mutable", sa.Boolean(), server_default="1", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "is_mutable")
    # ### end Alembic commands ###
