"""вместо Description создана таблица Event

Revision ID: 1944fd85b150
Revises: dd82341d478c
Create Date: 2025-02-07 12:00:59.470097

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1944fd85b150"
down_revision: Union[str, None] = "dd82341d478c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("moon_day", sa.String(length=10), nullable=True),
        sa.Column("en_name", sa.String(), nullable=False),
        sa.Column("ru_name", sa.String(), nullable=True),
        sa.Column("ru_text", sa.Text(), nullable=True),
        sa.Column("en_text", sa.Text(), nullable=True),
        sa.Column("link", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_events_id"), "events", ["id"], unique=True)
    op.create_table(
        "dayinfo_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("day_info_id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["day_info_id"],
            ["day_info.id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dayinfo_events")
    op.drop_index(op.f("ix_events_id"), table_name="events")
    op.drop_table("events")
    # ### end Alembic commands ###
