"""удалил Descriptions

Revision ID: 72b5baca7b9d
Revises: 1944fd85b150
Create Date: 2025-02-07 12:36:58.573130

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "72b5baca7b9d"
down_revision: Union[str, None] = "1944fd85b150"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_descriptions_id", table_name="descriptions")
    op.drop_table("descriptions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "descriptions",
        sa.Column("en_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("ru_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("ru_text", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("en_text", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("link", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("day_info_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["day_info_id"],
            ["day_info.id"],
            name="descriptions_day_info_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="descriptions_pkey"),
    )
    op.create_index("ix_descriptions_id", "descriptions", ["id"], unique=True)
    # ### end Alembic commands ###
