"""Изменена таблица элементов на сочетание пар

Revision ID: d261966e066f
Revises: 97e93f0b7c91
Create Date: 2025-02-04 10:28:07.525277

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d261966e066f"
down_revision: Union[str, None] = "97e93f0b7c91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("elements", sa.Column("en_name", sa.String(length=30), nullable=False))
    op.add_column("elements", sa.Column("ru_name", sa.String(length=30), nullable=False))
    op.add_column("elements", sa.Column("ru_text", sa.Text(), nullable=True))
    op.add_column("elements", sa.Column("en_text", sa.Text(), nullable=True))
    op.drop_constraint("elements_name_key", "elements", type_="unique")
    op.create_unique_constraint(None, "elements", ["ru_name"])
    op.create_unique_constraint(None, "elements", ["en_name"])
    op.drop_column("elements", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "elements", sa.Column("name", sa.VARCHAR(length=15), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "elements", type_="unique")
    op.drop_constraint(None, "elements", type_="unique")
    op.create_unique_constraint("elements_name_key", "elements", ["name"])
    op.drop_column("elements", "en_text")
    op.drop_column("elements", "ru_text")
    op.drop_column("elements", "ru_name")
    op.drop_column("elements", "en_name")
    # ### end Alembic commands ###
