"""Добавлены столбцы en_name, ru_text, en_text в таблицу Description

Revision ID: 97e93f0b7c91
Revises: 3f7063c41e76
Create Date: 2025-02-02 14:11:09.643933

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "97e93f0b7c91"
down_revision: Union[str, None] = "3f7063c41e76"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("descriptions", sa.Column("ru_name", sa.String(), nullable=True))
    op.add_column("descriptions", sa.Column("ru_text", sa.Text(), nullable=True))
    op.add_column("descriptions", sa.Column("en_text", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("descriptions", "en_text")
    op.drop_column("descriptions", "ru_text")
    op.drop_column("descriptions", "ru_name")
    # ### end Alembic commands ###
