"""Создана таблица Specialdays

Revision ID: 72e58c39666f
Revises: b790b83a218b
Create Date: 2025-02-04 15:21:21.032488

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "72e58c39666f"
down_revision: Union[str, None] = "b790b83a218b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "specialdays",
        sa.Column("moon_days", sa.String(length=10), nullable=True),
        sa.Column("en_name", sa.String(), nullable=False),
        sa.Column("ru_name", sa.String(), nullable=True),
        sa.Column("ru_text", sa.Text(), nullable=True),
        sa.Column("en_text", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_specialdays_id"), "specialdays", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_specialdays_id"), table_name="specialdays")
    op.drop_table("specialdays")
    # ### end Alembic commands ###
