"""Переименован столбец text

Revision ID: 3f7063c41e76
Revises: f7adf26e627c
Create Date: 2025-02-02 13:56:00.089998

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3f7063c41e76"
down_revision: Union[str, None] = "f7adf26e627c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("descriptions", "text", new_column_name="en_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("descriptions", "en_name", new_column_name="text")
    # ### end Alembic commands ###
