"""Добавлена колонка is_positive в таблицу элементов

Revision ID: 80a68c104c53
Revises: d261966e066f
Create Date: 2025-02-04 11:34:25.029043

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "80a68c104c53"
down_revision: Union[str, None] = "d261966e066f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("elements", sa.Column("is_positive", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("elements", "is_positive")
    # ### end Alembic commands ###
