"""Удали Specialdays

Revision ID: dd82341d478c
Revises: 72e58c39666f
Create Date: 2025-02-05 18:18:13.801778

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dd82341d478c"
down_revision: Union[str, None] = "72e58c39666f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_specialdays_id", table_name="specialdays")
    op.drop_table("specialdays")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "specialdays",
        sa.Column("moon_days", sa.VARCHAR(length=10), autoincrement=False, nullable=True),
        sa.Column("en_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("ru_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("ru_text", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("en_text", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="specialdays_pkey"),
    )
    op.create_index("ix_specialdays_id", "specialdays", ["id"], unique=True)
    # ### end Alembic commands ###
