version: '3.9'

services:

  db:
    image: postgres:latest
    ports:
      - '${APP_CONFIG__DB__PORT}:5432'
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${APP_CONFIG__DB__USER}"
      POSTGRES_PASSWORD: "${APP_CONFIG__DB__PASSWORD}"
      POSTGRES_DB: "${APP_CONFIG__DB__DATABASE}"
