name: Docker CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production  # ✅ Добавлено, чтобы были видны secrets из production
    env:
      PYTHON_VERSION: "3.11"
      NODE_VERSION: "18.x"
      DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/calendar-api

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    env:
      DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/calendar-api
      DB_PORT: 5432
      RUN_HOST: 0.0.0.0

    steps:
      - uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          known_hosts: unnecessary

      - name: Create .env file dynamically
        run: |
          cat << EOF > .env
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=5432
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_DATABASE=${{ secrets.DB_DATABASE }}
          SUPER_USER_EMAIL=${{ secrets.SUPER_USER_EMAIL }}
          SUPER_USER_PASSWORD=${{ secrets.SUPER_USER_PASSWORD }}
          ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}
          EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}
          EMAIL_PORT=${{ secrets.EMAIL_PORT }}
          EMAIL_HOST=${{ secrets.EMAIL_HOST }}
          CALENDAR_ID=${{ secrets.CALENDAR_ID }}
          CALENDAR_SECRET_FILE=${{ secrets.CALENDAR_SECRET_FILE }}
          YANDEX_DISK_TOKEN=${{ secrets.YANDEX_DISK_TOKEN }}
          RESET_PASSWORD_TOKEN_SECRET=${{ secrets.RESET_PASSWORD_TOKEN_SECRET }}
          VERIFICATION_TOKEN_SECRET=${{ secrets.VERIFICATION_TOKEN_SECRET }}
          SQL_ADMIN_SECRET=${{ secrets.SQL_ADMIN_SECRET }}
          SQL_ADMIN_JWT_SECRET=${{ secrets.SQL_ADMIN_JWT_SECRET }}
          DOCKER_IMAGE=${{ env.DOCKER_IMAGE }}
          EOF

      - name: Deploy to production
        run: |
          mkdir -p /tmp/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > /tmp/.ssh/id_rsa
          chmod 600 /tmp/.ssh/id_rsa
          ssh-keyscan ${{ secrets.SERVER_IP }} > /tmp/.ssh/known_hosts
          
          scp -o StrictHostKeyChecking=no \
              -i /tmp/.ssh/id_rsa \
              ./docker-compose.yml \
              ./.env \
              ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/${{ secrets.SERVER_USER }}
          
          ssh -o StrictHostKeyChecking=no \
              -i /tmp/.ssh/id_rsa \
              ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
                cd /home/${{ secrets.SERVER_USER }} &&
                docker-compose -f docker-compose.yml --env-file .env up -d --build &&
                rm .env  # Удаляем .env после использования
              "